### ISSUE TITLE
compute/lab: Replace `with event` constructs with regular locking

### ISSUE THREAD

**Issue by teodutu** [open-education-hub/operating-systems#131] opened 2023-02-11 09:58 UTC
[The support code for conditions](https://github.com/open-education-hub/operating-systems/blob/master/content/chapters/compute/lab/support/apache2-simulator/apache2_simulator_condition.py) uses `with event` constructs. They are confusing for students who don't have a good grasp on synchronisation mechanisms yet. They should be replaced with `event.acquire()`. and `event.release()` to make the code clearer. Also, update the [corresponding Markdown file](https://open-education-hub.github.io/operating-systems/Lab/Compute/Synchronization/content/synchronization#conditions) to remove the reference to the `with` statement.

**Comment by darius-m** [comment] 2023-02-11 18:50
The issue is not strictly related to the synchronization mechanisms themselves, but rather that the `with` statements automatically use context managers that lock or create resources at the start of the block, and release the resources when the block ends. This hides a lot of complexity behind Python-specific syntax, which makes it harder to follow, when considering most other languages do not have equivalent constructs.

While this is a really useful feature when coding Python, code snippets across the repository should probably use it sparingly, as it does not help understanding the underlying concepts (file opening and closing, synchronization mechanisms, etc.).

**Closed** 2023-04-15 13:35 UTC
Labels: student-contrib, area/content, area/code, kind/improve, topic/compute
